default_platform(:ios)

platform :ios do
  desc "Run all unit test"
  lane :test do
    scan(
      scheme: "DemoSurvey",
      devices: ["iPhone 8"],
      clean: true,
      skip_build: true
    )
  end
end
